### ISSUE TITLE
Create entity cause

### ISSUE THREAD

**Issue by rafestorn** [gii-is-psg2/psg2-2122-g4-44#48]
Create a Causes functionality. As a client, we can create a cause that contains a name and description (string), a budget target (numeric), and an active non-profit organization (string) that will use the budget for the cause.

**Comment by kwertyx** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2122-g4-44-62330b1c8aee360019d2405b/issues/gii-is-psg2/psg2-2122-g4-44/48?planning-poker) with ZenHub @alecarnun @rafestorn
