### ISSUE TITLE
Prepare a release

### ISSUE THREAD

**Issue by rafestorn** [gii-is-psg2/psg2-2122-g4-44#49]
As a group, once the previous changes are done, prepare a release of the Petclinic project, creating a corresponding release branch. In this release branch, all members of the group should remove any error and warning that is present in all source files of the developed code, up until the moment the release is started. As a final result of that release, the updated Petclinic application has to be deployed in Heroku, under the same URL as in the previous Sprint, i.e. https://psg2-2122-gx-xy.herokuapp.com/, where X-XY corresponds to the group id.

**Comment by kwertyx** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2122-g4-44-62330b1c8aee360019d2405b/issues/gii-is-psg2/psg2-2122-g4-44/49?planning-poker) with ZenHub @alecarnun @rafestorn

**Comment by rafestorn** [comment]
Desplegado a través de heroku cli
