### ISSUE TITLE
Create entity adoptionApplication

### ISSUE THREAD

**Issue by rafestorn** [gii-is-psg2/psg2-2122-g4-44#51]
Other owners could list the pets available for adoption and apply (adoption applications will have a description of how the applicant will take care of the pet). If the original owner approves the application, the pet will be transferred to the applicant and he/she will be the new owner of the pet.

**Comment by kwertyx** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2122-g4-44-62330b1c8aee360019d2405b/issues/gii-is-psg2/psg2-2122-g4-44/51?planning-poker) with ZenHub @alecarnun @rafestorn
