### ISSUE TITLE
Validation on the booking

### ISSUE THREAD

**Issue by rafestorn** [gii-is-psg2/psg2-2122-g4-44#53]
Implement a validation on the booking creation of your pet hotel functionality that ensures that there are no concurrent bookings in the hotel for the same pet.

**Comment by kwertyx** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2122-g4-44-62330b1c8aee360019d2405b/issues/gii-is-psg2/psg2-2122-g4-44/53?planning-poker) with ZenHub @alecarnun @rafestorn
