### ISSUE TITLE
Implement view causes section

### ISSUE THREAD

**Issue by rafestorn** [gii-is-psg2/psg2-2122-g4-44#54]
The application should have a “causes” section with a listing of causes, showing:
the name of the cause
the total budget achieved (sum of donations)
the budget target
a button for creating a donation
a button to navigate to a causes detail page
The causes detail page will show all the information about the cause including the details of each donation (date of donation, amount, and client). The causes detail page includes a donation button that will show a form to perform the donations.

**Comment by kwertyx** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2122-g4-44-62330b1c8aee360019d2405b/issues/gii-is-psg2/psg2-2122-g4-44/54?planning-poker) with ZenHub @alecarnun @rafestorn
