### ISSUE TITLE
Create entity donation

### ISSUE THREAD

**Issue by rafestorn** [gii-is-psg2/psg2-2122-g4-44#55]
Clients can do a donation of a specific amount to a cause until the total sum of donations reaches the budget target. Then the cause is closed and the money is transferred to the non-profit organisation (you don’t have to implement the transference).

**Comment by kwertyx** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2122-g4-44-62330b1c8aee360019d2405b/issues/gii-is-psg2/psg2-2122-g4-44/55?planning-poker) with ZenHub @alecarnun @rafestorn
