### ISSUE TITLE
Technical Report: "Métricas de Proceso Ágil y Recursos"

### ISSUE THREAD

**Issue by rafestorn** [gii-is-psg2/psg2-2122-g4-44#56]
As a group, create a technical report (in Spanish) entitled “Métricas de Proceso Ágil y Recursos”. This document must contain at least the following items:

For Sprint S2:
BurnDown chart,
total history points delivered,
percentage of history points delivered.
For Sprint S3:
BurnDown chart,
Control Chart showing Lead Time,
Control Chart showing Cycle time,
Total history points delivered,
Percentage of history points delivered,
Niko-niko calendar with a qualitative analysis of its content (conclusions and possible actions to improve team morale).

**Comment by kwertyx** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2122-g4-44-62330b1c8aee360019d2405b/issues/gii-is-psg2/psg2-2122-g4-44/56?planning-poker) with ZenHub @alecarnun @rafestorn
