### ISSUE TITLE
Technical Report Sprint S2

### ISSUE THREAD

**Issue by rafestorn** [gii-is-psg2/psg2-2122-g4-44#58]
For Sprint S2:
BurnDown chart,
total history points delivered,
percentage of history points delivered.

**Comment by kwertyx** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2122-g4-44-62330b1c8aee360019d2405b/issues/gii-is-psg2/psg2-2122-g4-44/58?planning-poker) with ZenHub @alecarnun @rafestorn
