### ISSUE TITLE
Technical Report: “Análisis del Código Fuente y Métricas Asociadas”

### ISSUE THREAD

**Issue by rafestorn** [gii-is-psg2/psg2-2122-g4-44#60]
As a group, create a technical report (in Spanish) entitled “Análisis del Código Fuente y Métricas Asociadas” on the results of analyzing your project with SonarCloud (as per the releases generated in S2 and S3, analyzing the code in the master branches for the corresponding commits). Such a report should describe the values of the source code metrics computed, the types of issues found in the analysis, and its causes. This document must contain at least the following items:

A screenshot of the Sonar Cloud dashboard for the analysis of your project and a description of the metrics provided in the dashboard and their values.
Description and analyses of the potential bugs found in the repository  (in the reliability section, on measures).
Description and analysis of the different types of code smells found in the analyses (in the maintainability section, on measures). For each type of code smell, the report should describe. 
The name and description of the code smell
The different causes of the smell in your codebase
A justified evaluation of the severity of the code smell
A brief description of how to solve it depending on the causes
Conclusions about the results of the analyses

**Comment by kwertyx** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2122-g4-44-62330b1c8aee360019d2405b/issues/gii-is-psg2/psg2-2122-g4-44/60?planning-poker) with ZenHub @alecarnun @rafestorn
