### ISSUE TITLE
A3.8: Documentation

### ISSUE THREAD

**Issue by alecarnun** [gii-is-psg2/psg2-2122-g4-44#64]

**Comment by kwertyx** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/psg2-2122-g4-44-62330b1c8aee360019d2405b/issues/gii-is-psg2/psg2-2122-g4-44/64?planning-poker) with ZenHub @alecarnun @rafestorn

**Comment by rafestorn** [comment]
Todas las tareas que la componen se han terminado.
